Repository eryajf/go-ldap-admin-ui, pull requests merged in 2022-07, with the labels that each got.

#11 修改README，修复一个问题
  README.md
  src/views/groupUser/userList/index.vue
Labels: documentation

#13 feat: 支持一键导入已经在运行openldap数据的能力
  src/api/personnel/group.js
  src/api/personnel/user.js
  src/views/personnel/group/index.vue
  src/views/personnel/user/index.vue
Labels: feature

#12 “新增字段关系”
  src/api/personnel/fieldRelation.js
  src/views/personnel/fieldRelation/index.vue
  vue.config.js
Labels: feature

#14 doc: 一些文案修改
  src/views/personnel/fieldRelation/index.vue
  src/views/personnel/group/index.vue
  src/views/personnel/user/index.vue
Labels: documentation

#15 🎊 readme中示例截图表格化呈现
  README.md
Labels: documentation

#17 ⚗️ readme添加徽标
  README.md
  src/utils/request.js
Labels: documentation

#19 [fix]修复了删除用户所属部门时，departments字段不会删除的问题
  src/views/personnel/user/index.vue
Labels: bug
